### ISSUE TITLE
Other tech (NPM) - discussion

### ISSUE THREAD

**Issue by mikestreety** [axllent/gitlabci-composer-update-mr#9]
Hey,

Thanks again for such a straight-forward great toolkit, it has saved me so much time!

This is where I start to get greedy and think "It would be great if...". After composer, the next task on my hit list was for automated `npm` updates. As I started thinking about it, this does everything I need except for the tech it is updating. It would be awesome if it could be another line in the `script` rather than being a whole new block with a whole different image (and me having to understand how Go works).

Is it something you would consider expanding into? 

I would be more than happy to work out the logistics of how it works - it already seems you have the Git, Gitlab and composer stuff separated but I wouldn't know where to start or how to test.

In terms of practicality behind it, the best thing I've found for updating NPM packages is [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) - I could imaging passing in parameters like you do to the composer one. 

The `.gitlab-ci.yml` file would look something like:

```yaml
update-mr:
  image: axllent/gitlabci-composer-update-mr:php-7.4-npm-14
  script:
    - gitlabci-composer-update-mr <commit-user> <commit-email> <source-branch>
    - gitlabci-npm-update-mr <commit-user> <commit-email> <source-branch> -t minor
```

I would imagine, it being a separate commit - not sure if it should be in the same MR though, depends how complex it would be to integrate. I also appreciate it would mean making a _lot_ more docker images (there is [this repo](https://github.com/t3easy/docker-surf) that does produce a lot of docker images like this - it also includes "surf" but you get the idea)

Just a thought/discussion - happy to help as much as I can or if it's something you don't want to pursue I understand/
